# Generated by Django 2.2.24 on 2021-11-20 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_event_ticket_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sold',
            field=models.BooleanField(),
        ),
        migrations.DeleteModel(
            name='Tweet',
        ),
    ]
