# Generated by Django 2.2.24 on 2021-11-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20211120_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
