# Generated by Django 3.0 on 2021-12-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20211208_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='num_tickets',
            field=models.IntegerField(default=0),
        ),
    ]
