# Generated by Django 3.0 on 2021-12-08 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_event_num_tickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lowest_ticket_price',
            field=models.FloatField(default=-1),
        ),
    ]
